version: "3.8"

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: app
  #   ports:
  #     - "${APP_PORT:-3000}:3000"
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     DB_HOST: ${DB_HOST}
  #     DB_PORT: ${DB_PORT}
  #     DB_USER: "${DB_USER}"
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     REDIS_PASSWORD: ${REDIS_PASSWORD}
  #     REDIS_HOST: ${REDIS_HOST}
  #     ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
  #     REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
  #     IS_DOCKER: "TRUE"
  #   depends_on:
  #     - postgres
  #     - redis
  #   restart: always
  #   networks:
  #     - app-network

  postgres:
    image: postgres:latest
    container_name: postgres-container
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
      interval: 10s
      timeout: 5s
      retries: 3
    # networks:
    #   - app-network

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis-data:/data
    restart: always
    # networks:
    #   - app-network

volumes:
  postgres-data:
  redis-data:

networks:
  app-network:
    driver: bridge
